### ISSUE TITLE
Alternative icon

### ISSUE THREAD

**Issue by radu-nh** [noonchen/BTT_AppleWirelessHeadphone#3]
Hi, 

is it possible to have an alternative icon when no headphones are connected?

**Comment by noonchen** [comment]
Hi,

Yes, it's possible, since only you are requesting this feature, I would simple told you how to modify the code instead of releasing a new version.

https://github.com/noonchen/BTT_AppleWirelessHeadphone/blob/eee6c92e7955c2487bdf1cae531b5c36e420f9f6/source/connect_appleBT.py#L66-L67
Headphone connection status can be retrieved by `connected`, you can simply add an `if` clause to return an icon immediately when `connected == False`:

```
    connected = True if BT_dict[devNAME][0] == "true" else False 
    if not connected:
        return jsonfy(icon_path=XXXXXXXX)
```
Replace the `XXXXXXXX` in the code above with the path of your alternative icon. The path should be an absolute path, for example, if your icon is located in `~/Download` folder, you should change the `return` line to `return jsonfy(icon_path="/Users/YourName/Downloads/icon.png")`

**Comment by radu-nh** [comment]
Thanks for showing me how to do this! :-)

**Comment by noonchen** [comment]
My pleasure :)
